# currentTools# ThreadLocalErr
#server:
#  tomcat:
#    max-threads: 1

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  groovy:
    template:
      check-template-location=false: